### ISSUE TITLE
Problem occurring while setting-up the local work environment

### ISSUE THREAD

**Issue by cristian-paris** [acs-pa/pa-lab#11]
In certain conditions (mostly on machines with a fresh install of linux/wsl/wsl2), there may be an issue where the checker fails to run the `./checker <lang> <task>` command (  `"Eroare: Nu am gasit python. Instaleaza python."`), even though `python` is present. The problem is caused by the explicit absence of the `python command` , which can be solved by doing `sudo apt install python-is-python2`  or `sudo apt install python-is-python3` and should be added in the `setup.md` file as an additional step.

**Comment by neatudarius** [comment]
Thank you for the report!

This issue was fixed in #17 .
